### ISSUE TITLE
merge uniq contigs

### ISSUE THREAD

**Issue by danshu** [mahulchak/quickmerge#11]
Would it be possible to merge those uniq contigs in reference assembly into query assembly ? By calling it "uniq" I mean those that have little overlap with any contigs in query assembly.

**Comment by mahulchak** [comment]
The current implementation of _quickmerge_ does not allow that. However, you can perform two rounds of quickmerge to incorporate all unique contigs from both assemblies in the final merged assembly. Please see the [wiki](https://github.com/mahulchak/quickmerge/wiki) for some suggestions on how to do it.

**Comment by danshu** [comment]
Two rounds of quickmerge can only improve the results, since the merging parameters are stringent. Quickmerge seems can only merge contigs with overlaps fulfilling stringent requirements. What I mean is to add contigs from the reference assembly into the query assembly when these contigs have little overlaps with any contigs in the query assembly (the filtering parameters can also be stringent).

**Comment by mahulchak** [comment]
Here is what I have understood about your problem. Please correct me if I am wrong.

You have contig X in the reference assembly that does not produce any significant alignment (>c) with your query assembly. You want this contig to be present in your final merged assembly. Is this correct? 

If my interpretations are correct, then there is a simple way of doing this (one that does not involve quickmerge).

Method1: You take the contig out from the reference assembly and add that to the merged assembly  manually. If you want to do this and need help, I can send you a script.

Method2: If you are trying to incorporate the contig from the reference assembly into the merged assembly without changing it, you can use the reference assembly as the query assembly and the the query assembly as the reference assembly. If you use the current reference assembly as the query assembly, the contigs that don't produce alignments above the -c cutoff are left unchanged.

Let me know if this made sense. If you could share the assemblies, then I can take a look at the issue.

Mahul

**Comment by danshu** [comment]
Yes, that's exactly what I mean.
For method 1, to manually incorporate contigs, I  want to keep the filtering parameters stringent while at the same time do not miss many useful contigs. I want to keep contig X in the reference assembly that does not produce any significant alignment (>c) with my query assembly. I also want to keep contig Y in the reference assembly that produce significant alignment (>c) with my query assembly due to repeats, if possible. 
For method 2, using reference assembly as the query assembly will keep some undesirable contigs in the merged assembly. 
Thanks for your help!

Quan
