### ISSUE TITLE
Output as 80 character standard FASTA

### ISSUE THREAD

**Issue by ccneko** [mahulchak/quickmerge#14]
Hello! Mahul

I am using the merge_wrapper.py approach.
I noticed that a second round of quickmerge from quickmerge output would not complete.
It stops after generating out.delta, without generating the final merged.fasta

It is found that by correcting the fasta from one-line sequence into standard 80 characters per line, the script can complete.

May I ask if I might've missed anything?
Or if it is possible to generate merged.fasta into 80 characters, or to let quickmerge accept one-line sequence?

Many thanks!

**Comment by mahulchak** [comment]
Hi,
I feel it has to do with the fasta file requirement of quickmerge. I have modified the code to apply a fix. Could you please download the latest version and see if the problem still persists?
Mahul

**Comment by ccneko** [comment]
Hi!
Re-ran with the new version, and it's fine now
Great, thanks! :)
