### ISSUE TITLE
Duplications

### ISSUE THREAD

**Issue by antben** [mahulchak/quickmerge#15]
Hi Mahul,

Based on BUSCO analysis, quickmerge is introducing duplications into my genome sequence. The original versions of my assemblies have 17 and 27 duplicated BUSCOs but, after quickmerge, there are 78 or 398 duplicated BUSCOs, depending on merge order. I tried the two-stage approach but the number of duplicated BUSCOs just keeps getting higher with each iteration. Any idea why this is happening or how I can remedy the situation? I have been running merge_wrapper.py with -hco 7 -c 2 -lm 5000 -l 5000000. My genome is from a bee and is ~400Mb (though the assemblies are closer to 300Mb) and known to be somewhat repetitive. My original assemblies are both pretty complete and are only missing ~2% of 4,415 BUSCOs.

Any help would be much appreciated.

Thanks,
Ben

**Comment by mahulchak** [comment]
Hi Ben,
Thanks for reprting the issue.
Do you think your fasta files can be shared so that I can take a look? What
happens if you increase ml to 20000? Are you using the latest version on
github?
Best,
Mahul

**Comment by antben** [comment]
Hi Mahul,
The two genome assemblies can be downloaded here: https://www.dropbox.com/s/izpyfkjpft79nve/calceatum_rand_1.fa.gz and here: https://www.dropbox.com/s/0ip6ncz4zvgkint/calceatum_rand_2.fa.gz

I guess I didn't have the absolute most recent version of quickmerge -- I downloaded it on November 29th. I'll download it again and try it with ml 20000. I should probably mention that my installation was a little buggy. When running "make", I got the error below. So I downloaded MUMmer directly (http://mummer.sourceforge.net/) and replaced the MUMmer directory in the quickmerge directory with the new copy. Then I used "make" on quickmerge and MUMmer individually. That seems to have remedied the compilation problem.

Also, I'm not sure if this is relevant but these assemblies were not made with PacBio but, rather, with 10x data. So they may be of a different structure than expected.

Thanks for the help!
Ben

The "make" error:
collect2: error: ld returned 1 exit status
chmod: cannot access '/home/ben/local/src/quickmerge/MUMmer3.23/delta-filter': No such file or directory
Makefile:60: recipe for target 'delta-filter' failed
make[1]: *** [delta-filter] Error 1
make[1]: Leaving directory '/home/ben/local/src/quickmerge/MUMmer3.23/src/tigr'
Makefile:125: recipe for target 'tigr' failed
make: *** [tigr] Error 2

**Comment by mahulchak** [comment]
Thanks for sharing the fasta files. I have downoaded the files. I have
never run quickmerge with 10X assemblies.   I will take a look and let you
know what I find. I am currently travelling so my response could be slow
sometimes.
Mahul

**Comment by antben** [comment]
Hi Mahul,

It looks like the problem has been solved by updating to the most recent
version on github. Thanks for the help!

Ben

On Tue, Dec 6, 2016 at 11:27 AM, Mahul Chakraborty <notifications@github.com
> wrote:

> Thanks for sharing the fasta files. I have downoaded the files. I have
> never run quickmerge with 10X assemblies. I will take a look and let you
> know what I find. I am currently travelling so my response could be slow
> sometimes.
> Mahul
>
>
>

**Comment by mahulchak** [comment]
Great :)
