### ISSUE TITLE
Redundancy introduced by Quickmerge?

### ISSUE THREAD

**Issue by danshu** [mahulchak/quickmerge#16]
Hi,

When using reference assembly to improve the hybrid assembly, e.g, contig A in the reference assembly can improve contig B in the hybrid assembly, will quickmerge further check if there are genomic equivalent of contig A in the hybrid assembly? If not, then there will be redundancy introduced by quickmerge.

Best,
Danshu

**Comment by mahulchak** [comment]
To answer your question in short: yes. Quickmerge now produces a file called "residuals.fasta". This file has  sequences that are alternate haplotypes (what you called as 'genomic equivalent') of some sequences or sequence segments present in the hybrid assembly. However, this is an experimental feature and therefore I can't guarantee its performance.

**Comment by danshu** [comment]
Thanks for you quick reply. By 'genomic equivalent' I mean the exact same sequence instead of alternate haplotypes. It is difficult to determine if something is alternate haplotype or not by sequence alignment alone. Just use the previous example again, when using contig A in the reference assembly to improve contig B in the hybrid assembly, will quickmerge remove any sequences in the hybrid assembly that are contained in contig A? 
The reason why I have this question is that the contig number remains unchanged while some contigs get longer after quickmerge.

**Comment by danshu** [comment]
In the paper it is mentioned that "Query contigs that are completely contained within a reference contig are also removed from the final merged assembly to prevent sequence duplication in the merged assembly". But I have noticed that some merged contigs have sequences highly similar to other contigs in the hybrid assembly.

**Comment by mahulchak** [comment]
you mean that in the final merged assembly there are contigs that are
highly similar to each other in which one is a merged contig and other
one(s) is hybrid contig?

**Comment by danshu** [comment]
Yes, and here are alignment results using minimap.
Seg941	794753	6975	27065	-	merged_Seg1	2658806	2638345	2658802	19783	20457	255	cm:i:3657
Seg941	794753	180900	424107	-	merged_Seg1	2658806	2242866	2483749	219967	243207	255	cm:i:40010
Seg941	794753	26921	181519	-	merged_Seg1	2658806	2482677	2636280	137981	154598	255	cm:i:25140
Seg941	794753	481312	540703	-	merged_Seg1	2658806	2130569	2189555	47802	59391	255	cm:i:8096
Seg941	794753	608977	715580	-	merged_Seg1	2658806	1956731	2063237	84572	106603	255	cm:i:15339
Seg941	794753	730159	745691	-	merged_Seg1	2658806	1925822	1941351	11763	15532	255	cm:i:1964
Seg941	794753	465137	485209	-	merged_Seg1	2658806	2185407	2204318	13527	20072	255	cm:i:2400
Seg941	794753	540668	613561	-	merged_Seg1	2658806	2057009	2129954	66636	72945	255	cm:i:11902
Seg941	794753	426183	474578	-	merged_Seg1	2658806	2195128	2242959	33371	48395	255	cm:i:5606
Seg941	794753	703416	716346	-	merged_Seg1	2658806	1956731	1969285	11559	12930	255	cm:i:1999
Seg941	794753	705040	730156	-	merged_Seg1	2658806	1943140	1967786	10697	25116	255	cm:i:1755
Seg994	2248806	1149769	1628589	-	merged_Seg1	2658806	1189716	1666912	451180	478820	255	cm:i:81833

**Comment by danshu** [comment]
┌────┬────────┬─────────────────────────────────────────────────────────────┐
                                │Col │  Type  │                         Description                         │
                                ├────┼────────┼─────────────────────────────────────────────────────────────┤
                                │  1 │ string │ Query sequence name                                         │
                                │  2 │  int   │ Query sequence length                                       │
                                │  3 │  int   │ Query start coordinate (0-based)                            │
                                │  4 │  int   │ Query end coordinate (0-based)                              │
                                │  5 │  char  │ `+' if query and target on the same strand; `-' if opposite │
                                │  6 │ string │ Target sequence name                                        │
                                │  7 │  int   │ Target sequence length                                      │
                                │  8 │  int   │ Target start coordinate on the original strand              │
                                │  9 │  int   │ Target end coordinate on the original strand                │
                                │ 10 │  int   │ Number of matching bases in the mapping                     │
                                │ 11 │  int   │ Number bases, including gaps, in the mapping                │
                                │ 12 │  int   │ Mapping quality (0-255 with 255 for missing)                │
                                └────┴────────┴─────────────────────────────────────────────────────────────┘
Alignment format

**Comment by mahulchak** [comment]
Could you please align the two contigs with nucmer and attach the delta
file?

**Comment by mahulchak** [comment]
when you run nucmer, please use the merged contig as the reference sequence.

**Comment by danshu** [comment]
nucmer -l 100 -prefix test Seg994.fasta target.fasta

merged_Seg1.fasta Seg994.fasta
NUCMER
>merged_Seg1 Seg994 2658806 2248806
544984 555139 2248806 2238651 5 5 0
-692
16
-16
492
0

**Comment by mahulchak** [comment]
is that all of the delta file ?

**Comment by danshu** [comment]
yes.

This may not be a good example. I just find another hybrid contig in the merged.fasta that is highly similar to a merged contig.
Here is the alignment using minimap:
Seg481	51259	1	51256	-	merged_Seg1	2658806	1910244	1961531	47437	51287	255	cm:i:8774

Alignment using nucmer:
>merged_Seg1 Seg481 2658806 51259
1910242 1920391 51259 41139 118 118 0
151
370
115
109
240
-96
237
29
14
74
353
120
25
227
112
999
115
1
406
1
299
19
23
90
24
180
94
137
19
118
15
-103
19
23
-11
19
221
9
-34
45
151
35
77
36
5
53
79
88
-13
36
24
9
-109
165
378
10
-213
-245
-69
-16
-12
-5
-7
-18
-4
-7
-9
12
-116
-43
-368
-9
-35
0

**Comment by mahulchak** [comment]
I think part of your delta files are getting chopped so it is currently
showing only the first segment of the alignment. Instead of copy pasting
the content of the delta file, could you please attach and send to me. Or
else, you can email me the delta file at mchakrab@uci.edu

**Comment by danshu** [comment]
[Seg994.txt](https://github.com/mahulchak/quickmerge/files/775846/Seg994.txt)
[Seg481.txt](https://github.com/mahulchak/quickmerge/files/775847/Seg481.txt)

**Comment by mahulchak** [comment]
Danshu,
for both of these sequences, I don't see end to end alignment of the hybrid
contig to the merged contig. The alignments are relatively short compared
to the length of the contigs and could be repeats or duplicated genes.
e.g. merged_Seg1 Seg481 alignment goes for 1910242 to 1920391 in the merged
contig and 51259 to 41139 in the hybrid contig. This alignment is only
10Kbp long.

**Comment by danshu** [comment]
Thanks!
