### ISSUE TITLE
merge_wrapper.py  run errors

### ISSUE THREAD

**Issue by Sisov** [mahulchak/quickmerge#18]
Dear author;
  while I use the quickmerge software ,it appears some errors that confused me a while .here is the error :

4: FINISHING DATA
Traceback (most recent call last):
  File "/public1/home/testuser/genome_Aessmblysoftware/quickmerge-master/merge_wrapper.py", line 174, in <module>
    subprocess.call(mergercall)
  File "/public1/home/testuser/miniconda2/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/public1/home/testuser/miniconda2/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/public1/home/testuser/miniconda2/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

 while my command is  merge_wrapper.py p_ctg.fa  SUNSET.contigs.fasta >merge.fasta
Can someone help me to solve it?
Thanks
Alex

**Comment by mahulchak** [comment]
Hi Alex,
Could you please check that nucmer and quickmerge are in your paths?
E.g. what happens when you type nucmer or quickmerge and then press enter?
Mahul

**Comment by RxLoutre** [comment]
Hi Mahul !

I had the same error than above.

Adding quickmerge to my path worked perfect for me !

Cheers,

Roxane

**Comment by jgbaldwinbrown** [comment]
Hi all,

Great to hear that that worked. I tested the error, and also found that adding quickmerge to my path solved the problem. The two things that need to be in your PATH are the directories containing quickmerge and nucmer. If you're new to unix, you can add things to your path in bash as follows:

export PATH=$PATH:/path/to/dir/containing/needed/executable

Hope this solves the problem.

Cheers,
Jim
