### ISSUE TITLE
slightly off-topic -- curious about your finisherSC recommendation

### ISSUE THREAD

**Issue by JohnUrban** [mahulchak/quickmerge#19]
Hello,

Thanks for the great tool.

I was curious -- since you recommend finisherSC, I was wondering if you have done any evaluations on the results? Do you have a feel for whether it introduces mis-assemblies and at what rate? etc.

I have read the finisherSC paper -- but I am curious about independent feedback to see if I should include it as part of a de novo assembly I am doing...

Best,

  John

**Comment by mahulchak** [comment]
Hi John,
I haven't really evaluated the tool like we have done for hybrid and PacBio assemblers. From my personal experience, I have seen finisherSC introducing large scale mis-assemblies only rarely. It may introduce small errors but I haven't really measured the extent of such errors.
Mahul

**Comment by JohnUrban** [comment]
Thanks Mahul. 

Since you are working with "larger" genomes (e.g. than E coli), were you forced to try the --large and/or --fast options? I'm also curious about whether you dealt with any excessively long runtime issues for finisherSC.

**Comment by mahulchak** [comment]
I used --large but I don't use the --fast option. I use 48-72 cores for
this and for the fly genomes it takes a day or two, depending on whether I
am running on AMD or Intel node. If it's been running for too long, then
may be something is not right. I think it's better to chat on this through
email or on finisher's github page. my email is mchakrab@uci[at]edu

**Comment by JohnUrban** [comment]
Will do - thanks
