### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by MichelMoser** [mahulchak/quickmerge#2]
Hi, 

I try to run quickmerge with two wgs-assemblies of a1.4 Gb genome but run into a segmentation fault in the merge step. N50 of the assemblies is about 200 Kb.

my commands:
```
nucmer -l  100 -prefix out pex_1.ctg.fasta pex_2.ctg.fasta

delta-filter -i 95 -r -q out.delta > out.rq.delta

quickmerge -d out.rq.delta -q pex_2.ctg.fasta -r pex_1.ctg.fasta -hco 5 -c 1.5 -l 200000
```

The stderror is unfortunately not very informative: 
```
/opt/sge/default/spool/binfservas12/job_scripts/116904: line 14: 99325 Segmentation fault      /home/mmoser/quickmerge/merger/quickmerge -d out.rq.delta -q pex_2.ctg.fasta -r pex_1.ctg.fasta -hco 5 -c 1.5 -l 200000
```
Stdout contains a list of 37 contigs present in  anchor_summary.txt (which has anchors for 1172 contigs).

Hope to get a clue how to resolve this problem. I ran everything on a SGE cluster. RAM usage didnt seem to be too high when the job terminated. 

Thank you, 
Michel

**Comment by MichelMoser** [comment]
just ran debugger gdb. segmentation fault seems to arise at line 509 of qmergelib.cpp

```
Peex101Ctg00225
Peex101Ctg00236
Peex101Ctg00241
Peex101Ctg00256
Peex101Ctg00258
Peex101Ctg00274
Peex101Ctg00284
Peex101Ctg00287

Program received signal SIGSEGV, Segmentation fault.
0x000000000040d7fe in longestLeft (tempname=..., seq=..., merge=..., RorQ=82 'R', sideQ=82 'R', prevElem=...) at qmergelib.cpp:509
509                                     size = merge.ovrHangQR[str][0];
(gdb) l
504                     }
505                    if(RorQ == 'R') //if looking for reference overhang length
506                     {
507                             if(merge.ovrHangR[str] == -1) // if query is innie
508                             {
509                                     size = merge.ovrHangQR[str][0];
510                             }
511                             if((merge.strandInfo[str] == merge.strandInfo[prevElem]) && (merge.ovrHangR[str] != -1)) //if the references for the query are on the same strand
512                             {
513                                     if(merge.sideInfo[str] != merge.sideInfo[prevElem]) // they ought to be different
(gdb) p str
$1 = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x16f1ebba8 "Peex101Ctg01323 ctg7180000037795"}}
```

when i grep for Peex101Ctg01323 it doesnt look strange at all to me:

```
[mmoser@binfservas06 quickmerge]$ grep Peex101Ctg01323 aln_summary.tsv 
Peex101Ctg01323  ctg7180000026094       507652  83254   1       83304   1       83254
Peex101Ctg01323  ctg7180000037795       507652  994141  121964  358533  385689  149204
Peex101Ctg01323  ctg7180000037795       507652  994141  358638  502313  148930  5231
Peex101Ctg01323  ctg7180000037795       507652  994141  502443  507652  5210    1
Peex101Ctg01323  ctg7180000039966       507652  57727   70249   126165  1       55897
[mmoser@binfservas06 quickmerge]$ grep Peex101Ctg01323 anchor_summary.txt 
Peex101Ctg01323  ctg7180000026094       507652  83254   1       83304   1       83254
Peex101Ctg01323  ctg7180000039966       507652  57727   70249   126165  1       55897
[mmoser@binfservas06 quickmerge]$ grep -a  Peex101Ctg01323 summaryOut.txt 
Peex101Ctg01323  ctg7180000026094       1       83304   1       83254   L       1       83253   83253   1       0
Peex101Ctg01323  ctg7180000037795       121964  507652  385689  1       L       0       385393  3.15987 121965  486488
Peex101Ctg01323  ctg7180000039966       70249   126165  1       55897   L       1       55896   30.5276 1831    0
```


another strange thing is that summaryOut.txt contains some '^@' signs in the orientation column:

```
Peex101Ctg00308  ctg7180000037797       6998    24290   3       17300   L       1       17297   5765.67 3       0
Peex101Ctg00308  ctg7180000037798       10551   302565  2       292013  R       1       292011  146006  2       0
Peex101Ctg11401  ctg7180000037799       1       560791  1       560791  ^@      1       560790  560790  1       0
Peex101Ctg11402  ctg7180000037800       1       16818   1       16818   R       0       16817   16817   1       444334
Peex101Ctg09590  ctg7180000037800       1       454772  6380    461152  L       0       454772  454772  1       6379
Peex101Ctg15733  ctg7180000037801       1       186119  1       186119  ^@      1       186118  186118  1       0
Peex101Ctg15734  ctg7180000037802       1       308624  1       308533  R       0       308532  121.998 2529    333254
Peex101Ctg00345  ctg7180000037802       3317    332533  308989  638234  L       0       329245  99.2599 3317    -1
```

**Comment by mahulchak** [comment]
Hi Michel,
looks like it's a bug. I'll check the code and create a fix.
Thanks for sharing the issue and running gdb.
Mahul

**Comment by mahulchak** [comment]
Hi Michel,

I think the line 353 is the root of the problem you encountered. could you
please try this?

edit the line 229 and 241 in the source code of qmergelib.cpp:

Current:
noRovl = q_last;

Change to:
noRovl = q_last -1;

You will have to recompile quickmerge after this (use "make" or "g++ -Wall
qmergelib.cpp quickmerge.cpp -o quickmerge" )

Let me know how it goes.
Mahul

On Thu, Nov 26, 2015 at 2:03 PM, mahul chakraborty <mahulchak@gmail.com>
wrote:

> Hi Michel,
> looks like it's a bug. I'll check the code and create a fix.
> Thanks for sharing the issue and running gdb.
> Mahul
>
> On Thu, Nov 26, 2015, 5:42 AM MichelMoser <notifications@github.com>
> wrote:
>
>> just ran debugger gdb. segmentation fault seems to arise at line 509 of
>> qmergelib.cpp
>>
>> Peex101Ctg00225
>> Peex101Ctg00236
>> Peex101Ctg00241
>> Peex101Ctg00256
>> Peex101Ctg00258
>> Peex101Ctg00274
>> Peex101Ctg00284
>> Peex101Ctg00287
>>
>> Program received signal SIGSEGV, Segmentation fault.
>> 0x000000000040d7fe in longestLeft (tempname=..., seq=..., merge=..., RorQ=82 'R', sideQ=82 'R', prevElem=...) at qmergelib.cpp:509
>> 509                                     size = merge.ovrHangQR[str][0];
>> (gdb) l
>> 504                     }
>> 505                    if(RorQ == 'R') //if looking for reference overhang length
>> 506                     {
>> 507                             if(merge.ovrHangR[str] == -1) // if query is innie
>> 508                             {
>> 509                                     size = merge.ovrHangQR[str][0];
>> 510                             }
>> 511                             if((merge.strandInfo[str] == merge.strandInfo[prevElem]) && (merge.ovrHangR[str] != -1)) //if the references for the query are on the same strand
>> 512                             {
>> 513                                     if(merge.sideInfo[str] != merge.sideInfo[prevElem]) // they ought to be different
>> (gdb) p str
>> $1 = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x16f1ebba8 "Peex101Ctg01323 ctg7180000037795"}}
>>
>> when i grep for Peex101Ctg01323 it doesnt look strange at all to me:
>>
>> [mmoser@binfservas06 quickmerge]$ grep Peex101Ctg01323 aln_summary.tsv
>> Peex101Ctg01323  ctg7180000026094       507652  83254   1       83304   1       83254
>> Peex101Ctg01323  ctg7180000037795       507652  994141  121964  358533  385689  149204
>> Peex101Ctg01323  ctg7180000037795       507652  994141  358638  502313  148930  5231
>> Peex101Ctg01323  ctg7180000037795       507652  994141  502443  507652  5210    1
>> Peex101Ctg01323  ctg7180000039966       507652  57727   70249   126165  1       55897
>> [mmoser@binfservas06 quickmerge]$ grep Peex101Ctg01323 anchor_summary.txt
>> Peex101Ctg01323  ctg7180000026094       507652  83254   1       83304   1       83254
>> Peex101Ctg01323  ctg7180000039966       507652  57727   70249   126165  1       55897
>> [mmoser@binfservas06 quickmerge]$ grep -a  Peex101Ctg01323 summaryOut.txt
>> Peex101Ctg01323  ctg7180000026094       1       83304   1       83254   L       1       83253   83253   1       0
>> Peex101Ctg01323  ctg7180000037795       121964  507652  385689  1       L       0       385393  3.15987 121965  486488
>> Peex101Ctg01323  ctg7180000039966       70249   126165  1       55897   L       1       55896   30.5276 1831    0
>>
>> another strange thing is that summaryOut.txt contains some '^@' signs in
>> the orientation column:
>>
>> Peex101Ctg00308  ctg7180000037797       6998    24290   3       17300   L       1       17297   5765.67 3       0
>> Peex101Ctg00308  ctg7180000037798       10551   302565  2       292013  R       1       292011  146006  2       0
>> Peex101Ctg11401  ctg7180000037799       1       560791  1       560791  ^@      1       560790  560790  1       0
>> Peex101Ctg11402  ctg7180000037800       1       16818   1       16818   R       0       16817   16817   1       444334
>> Peex101Ctg09590  ctg7180000037800       1       454772  6380    461152  L       0       454772  454772  1       6379
>> Peex101Ctg15733  ctg7180000037801       1       186119  1       186119  ^@      1       186118  186118  1       0
>> Peex101Ctg15734  ctg7180000037802       1       308624  1       308533  R       0       308532  121.998 2529    333254
>> Peex101Ctg00345  ctg7180000037802       3317    332533  308989  638234  L       0       329245  99.2599 3317    -1
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mahulchak/quickmerge/issues/2#issuecomment-159902739>
>> .
>>
>


-- 
Mahul Chakraborty
Emerson lab <http://emersonlab.org/>
Department of Ecology and Evolutionary Biology
University of California-Irvine
Phone: 949 824 9559
Fax:
Github: https://github.com/mahulchak

**Comment by MichelMoser** [comment]
Thanks for the code. Unfortunately not solved the problem yet.
With the altered code, i get 26 additional sequences in the stdout before termination. 
Segmentation fault now is on line 498: 

```
Peex101Ctg00390
Peex101Ctg00392
Peex101Ctg00408
Peex101Ctg00409
Peex101Ctg00410
Peex101Ctg00418
Peex101Ctg00434
Peex101Ctg00436
Peex101Ctg00446
Peex101Ctg00452
Peex101Ctg00462
Peex101Ctg00487
Peex101Ctg00495
Peex101Ctg00502
Peex101Ctg00507
Peex101Ctg00518

Program received signal SIGSEGV, Segmentation fault.
0x000000000040535f in longestLeft (tempname=..., seq=..., merge=..., RorQ=81 'Q', sideQ=78 'N', prevElem=...) at qmergelib.cpp:498
498                                     size =  merge.ovrHangQR[str][0]; //left overhang is the first element
(gdb) p str
$1 = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x16f1ed1b8 "Peex101Ctg00522 ctg7180000039853"}}
```

failing sequence looks like this in summaryOut.txt: 
```
 grep -a Peex101Ctg00522 summaryOut.txt                                                                                                                                                                      
Peex101Ctg00522  ctg7180000036005       219744  821940  602213  1       R       0       602212  150553  4       -3
Peex101Ctg00522  ctg7180000039848       208878  229890  20805   1       L       1       19938   inf     0       0
Peex101Ctg00522  ctg7180000039849       125525  209942  84545   1       L       1       84544   inf     0       0
Peex101Ctg00522  ctg7180000039850       115886  131964  16050   3       L       1       16047   8023.5  2       0
Peex101Ctg00522  ctg7180000039853       1       125126  125174  1       L       0       125173  62586.5 2       -1
```
what does inf mean in the 10th column? inf high probablity of match? 
Tell me if you need the original files or more information. 
Thank you!

**Comment by mahulchak** [comment]
Inf in the 10th column means that the HCO ratio is INF (nOVL is 0).
If you are able to share the files, that would be great.
Thank you.
Mahul


On Mon, Nov 30, 2015 at 2:49 AM, MichelMoser <notifications@github.com>
wrote:

> Thanks for the code. Unfortunately not solved the problem yet.
> With the altered code, i get 26 additional sequences in the stdout before
> termination.
> Segmentation fault now is on line 498:
>
> Peex101Ctg00390
> Peex101Ctg00392
> Peex101Ctg00408
> Peex101Ctg00409
> Peex101Ctg00410
> Peex101Ctg00418
> Peex101Ctg00434
> Peex101Ctg00436
> Peex101Ctg00446
> Peex101Ctg00452
> Peex101Ctg00462
> Peex101Ctg00487
> Peex101Ctg00495
> Peex101Ctg00502
> Peex101Ctg00507
> Peex101Ctg00518
>
> Program received signal SIGSEGV, Segmentation fault.
> 0x000000000040535f in longestLeft (tempname=..., seq=..., merge=..., RorQ=81 'Q', sideQ=78 'N', prevElem=...) at qmergelib.cpp:498
> 498                                     size =  merge.ovrHangQR[str][0]; //left overhang is the first element
> (gdb) p str
> $1 = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x16f1ed1b8 "Peex101Ctg00522 ctg7180000039853"}}
>
> failing sequence looks like this in summaryOut.txt:
>
>  grep -a Peex101Ctg00522 summaryOut.txt
> Peex101Ctg00522  ctg7180000036005       219744  821940  602213  1       R       0       602212  150553  4       -3
> Peex101Ctg00522  ctg7180000039848       208878  229890  20805   1       L       1       19938   inf     0       0
> Peex101Ctg00522  ctg7180000039849       125525  209942  84545   1       L       1       84544   inf     0       0
> Peex101Ctg00522  ctg7180000039850       115886  131964  16050   3       L       1       16047   8023.5  2       0
> Peex101Ctg00522  ctg7180000039853       1       125126  125174  1       L       0       125173  62586.5 2       -1
>
> what does inf mean in the 10th column? inf high probablity of match?
> Tell me if you need the original files or more information.
> Thank you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mahulchak/quickmerge/issues/2#issuecomment-160595798>.
>



-- 
Mahul Chakraborty
Emerson lab <http://emersonlab.org/>
Department of Ecology and Evolutionary Biology
University of California-Irvine
Phone: 949 824 9559
Fax:
Github: https://github.com/mahulchak

**Comment by MichelMoser** [comment]
Could you give me your email so i can send you dropbox links of the files?

**Comment by mahulchak** [comment]
Hi Michel,
you can send it to -
mchakrab@uci.edu
Also, I just pushed a couple of edits to qmergelib.cpp based on your last
message. Could you please check if that fixes the problem?
Thank you.
Mahul

**Comment by MichelMoser** [comment]
Thank you. Just saw that there is a compilation error: 
```
g++ -Wall -o quickmerge quickmerge.cpp qmergelib.cpp -I.
qmergelib.cpp: In function ‘void ovrHngCal(asmMerge&)’:
qmergelib.cpp:325:38: error: expected ‘;’ before ‘{’ token
  357                                 {
                                      ^
qmergelib.cpp:327:38: warning: statement has no effect [-Wunused-value]
  359                                 }
                                      ^
qmergelib.cpp:328:38: error: expected ‘;’ before ‘if’
  360                                 if(ovrhangR == -1)
                                      ^
qmergelib.cpp:331:38: warning: statement has no effect [-Wunused-value]
  363                                 }
                                      ^
make: *** [quickmerge] Error 1
````

**Comment by mahulchak** [comment]
Oh! the line numbers somehow got printed from line 325 to line 331. the
numbers "357,358,359,360,361,,362,363" need to be removed.
instead of -

357                                 {
 358                                         ovrhangQ = 0 ;
359                                 }
360                                 if(ovrhangR == -1)
361                                 {
362                                         ovrhangR = 0;
363                                 }

it will be
                                      {
                                              ovrhangQ = 0 ;
                                      }
                                     if(ovrhangR == -1)
                                    {
                                             ovrhangR = 0;
                                    }

**Comment by MichelMoser** [comment]
yes, saw that :) So the run now terminates with: 
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 442744) > this->size() (which is 0)
/opt/sge/default/spool/binfservas08/job_scripts/118783: line 14: 49041 Aborted                 /home/mmoser/quickmerge/merger/quickmerge -d out.rq.98.delta -q /data1/projects/p023/CELERA/Petunia/2nd_assembly/Pex_assembly2/9-terminator/pex_2.ctg.fasta -r /data1/projects/p023/P.EXSERTA/quickmerge/pe_ex101.ctg.fasta -hco 5 -c 1.5 -l 200000
```
stdout is now having 1841 lines of contig names printed and anchor-summary has 1852 lines. so i guess that the program ran through it and just terminated before creating output.

**Comment by mahulchak** [comment]
ah! that means the program was at the last stage when it crashed. Looks
like I'll need those files afterall :(
Meanwhile, you can play with the length, c,hco parameters to see if you can
bypass the error (change the parameters so that merging becomes more
restrictive)

**Comment by MichelMoser** [comment]
It works! 
Last error seems to be due only to my ignorance of the fasta format (joined lines instead of split lines). 
I could now create merged fasta files for a range of parameters without any complications. 
Thank you for the support.
