### ISSUE TITLE
nucmer parameters for large genome

### ISSUE THREAD

**Issue by blsfoxfox** [mahulchak/quickmerge#20]
Hi,

I am running quickmerge on an eukaryotic genome, which is around 1Gb. I got two assemblies from Canu (960Mb) and Miniasm( 870Mb). 
By using the default parameters of quickmerge, the merged assembly is ~1Gb and N50 is 3Mb, and I am quite satisfied with the metrics . However, as I would like to study the chromosome structure of this species, it is really important to have the orientation of the merged contigs as accurate as possible. 
Thus, could you provide any suggestion for the nucmer parameters to exclude mismerge for such big genome? I am re-running quickmerge with nucmer --maxmatch -c 500 -l 100, however, it is still difficult to determine how stringent should it be.

Thanks,

**Comment by mahulchak** [comment]
Hi,
If your canu and miniasm assemblies don't disagree with each other at large
scale (i.e. any of them does not possess a large scale scale misassembly),
then the merged assembly should have correct order and orientation. You
could run quickmerge with different l and ml parameter to see if you see
any major changes in the merged assembly. It is better to be conservative
for those parameters.
Let me know if you have any other question.
Mahul

**Comment by blsfoxfox** [comment]
Hi Mahul,

Thanks for your response and I will quickly run it.

Best,

blsfoxfox
