### ISSUE TITLE
Increasing contiguity further

### ISSUE THREAD

**Issue by jaworskicoline** [mahulchak/quickmerge#24]
Hello,
I am trying to create an extremely contiguous (chromosome-size) genome for a Drosophila, using the pipeline proposed in your 2016 paper. It has done very well so far, I have 3 chromosomes almost fully resolved, but the 4th one is in 3 fragments. I am wondering if there would be a way to stitch together those 3 fragments, for instance, by rerunning quickmerge on the final assembly (or just the 3 fragments extracted from that assembly) and one of the two assemblies (likely the PB only assembly, I guess those gaps are present in the hybrid assembly anyway), but with less stringent parameters. Do you have experience and/or advices for such a procedure ? Would that decrease the quality of the assembly in other parts than the ends of the fragments that need to be stitched together ? How to chose the parameters in this context (or just play around and compare the output ?) ?

Alternatively, I was thinking about using the raw reads again on those specific fragment ends and try to extend them through a consensus-calling method, would you have some tools/programs in mind that would do that ?

Thank you very much !
Best regards,
Coline

**Comment by mahulchak** [comment]
Hi Coline,
I would advise against forced merging because they are very likely to
introduce errors. You can try finisherSC (mentioned in quickmerge manual)
to check if there are raw reads that can improve contiguity further.
Cheers,
Mahul

**Comment by jaworskicoline** [comment]
Thanks,
I will look into this option.
Best,
Coline
