### ISSUE TITLE
merged.fasta the same as hybrid_assembly.fasta

### ISSUE THREAD

**Issue by peterdfields** [mahulchak/quickmerge#25]
Hi,

I'm trying to run quickmerge with an assembly generated with dbg2olc and canu. I run both the wrapper script and individual steps as described on the readme. I don't receive any errors. I do notice that the resultant merged.fasta has the same content exactly as the hybrid_assembly.fasta. I can also see that while the summaryOut.txt and aln_summary.tsv seem normal anchor_summary.txt file is empty except for a header line. Please let me know if any additional info would be useful in determine why the merging doesn't seem to be working.

**Comment by esolares** [comment]
Hi,

Thank you for your email. Could you please share your entire run
options/parameters/script for running nucmer and quickmerge.

Thank you

**Comment by peterdfields** [comment]
Sure. First I sourced the .quickmergerc, then:

for the wrapper:
`merge_wrapper.py hybrid_assembly.fasta self_assembly.fasta`

which finished with no errors.

Then with individual steps as:

```
nucmer -l 100 -prefix out self_assembly.fasta hybrid_assembly.fasta
delta-filter -i 95 -r -q out.delta > out.rq.delta
quickmerge -d out.rq.delta -q hybrid_assembly.fasta -r self_assembly.fasta -hco 5.0 -c 1.5 -l 400000 -ml 5000
```
which also didn't show any errors. Both resulted in the same output content described above.

**Comment by mahulchak** [comment]
Can you see the alignment in the out.rq.delta filea with mummerplot ?
You can do
mummerplot -fat -filter out.rq.delta

**Comment by peterdfields** [comment]
Yes. Would it be useful to upload this file?

**Comment by mahulchak** [comment]
Sure. If you can share the delta file, that would be great. Is 400kb n50 of
your self-assembly file?

**Comment by peterdfields** [comment]
You can download the file using the following link:
https://www.dropbox.com/s/5qlld3k2m0n4da4/out.rq.delta.gz

And the 400kb n50 is from the self-assembly file.

**Comment by mahulchak** [comment]
Hi,
I checked your delta file. There are no overlap that shows >5 HCO value,
and therefore no merging. Are you sure the assemblies are from the same
strain/species?
Mahul

**Comment by peterdfields** [comment]
The reads almost certainly derive from the same species. One point that could be important is that the self_assembly.fasta is almost 50% larger than the expected genome size, which is probably the result of redundancy in the assembly. Do you think this redundancy could result in the type of whole genome alignment results being observed here?

**Comment by mahulchak** [comment]
If there is high homology between the two assemblies then it should show HCO >5. Will you be able to share the fasta files so that we can investigate this a little more. We will use your files only to understand the problem and will not share it with anyone else. Let us know.

**Comment by peterdfields** [comment]
Do you have a preferred email address where the files could be sent to?

**Comment by mahulchak** [comment]
Please send them to mchakrab[at]uci.edu
