### ISSUE TITLE
the result

### ISSUE THREAD

**Issue by wenjiexiaomeng** [mahulchak/quickmerge#26]
>scaffold100000|size4398 C27495846419.0 4398 287
1003 1288 287 1 1 1 0-2400
>scaffold100000|size4398 C27567557919.0 4398 322
1800 2026 322 95 2 2 0-1000
>scaffold100000|size4398 scaffold13097019.4 4398 3412
2129 2283 167 10 4 4 0-112-1-250
>scaffold100000|size4398 scaffold44576520.6 4398 5548
1458 1695 3065 2826 3 3 0-202-3203867 4222 1115 757 7 7 0-14124-71-2332-58-60
>scaffold100001|size4398 C2721590907.0 4398 209
4144 4248 140 36 0 0 00
>scaffold100001|size4398 scaffold133571412.7 4398 1391
3481 4011 809 1347 28 28 0-216-1-1-1-1-1-1-1166-80
>scaffold100001|size4398 scaffold4287048.3 4398 1847
525 792 269 4 7 7 025-1054511-460
>scaffold100001|size4398 scaffold86268516.5 4398 1028
1381 1726 281 627 8 8 0-24-1720
>scaffold100002|size4398 C27479571713.0 4398 281
584 858 281 7 0 0 00
>scaffold100003|size4398 C27185330824.0 4398 203
931 1133 1 203 1 1 00
##############################################333

This is the result in my merged.fasta, what does this mean?
 I thought may be there are some problems here....

**Comment by mahulchak** [comment]
Could you please describe the commands and steps you used ?

**Comment by wenjiexiaomeng** [comment]
Hi,
These are my commands:
#############################################################################
/def/software/quickmerge-master/MUMmer3.23/nucmer --mum -c 100 -D 5 -d 0.12 --extend -g 90 -l 100 -p qingxia_nucmer qingxia_bwa.final.scaffolds.fasta qingxia.scafSeq
/def/software/quickmerge-master/MUMmer3.23/delta-filter -i 50 -l 100 -m -q -u 50 qingxia_nucmer.delta>out_qingxia.delta.out
/def/software/quickmerge-master/quickmerge -d qingxia_bwa.final.scaffolds.fasta -q out_qingxia.delta.out -r qingxia.scafSeq -hco 0.5 -c 1.5 -l 20000 -ml 20000
############################################################################
I ran this step by step, and there were no errors .
I noticed that there are some spaces in my scaffold name so I rename them and running it again.Would this be the reason?
Thanks for your help.

Best,
Wenjie

**Comment by mahulchak** [comment]
Hi Wenjie,
I would recommend you to follow the nucmer and quickmerge commands as described in the GitHub manual first and then you can tweak them as you wish.
following your files names, I am guessing qingxia_bwa.final.scaffolds.fasta and qingxia.scafSeq are the two assemblies? I am a little confused by the file name "qingxia.scafSeq". Are you sure that it is a fasta file ? Please run nucmer and delta-filter with the parameters as mentioned in the manual.

To run quickmerge, please follow the order of the commands as mentioned in the manual. E.g.
quickmerge -d out_qingxia.delta.out -q qingxia.scafSeq -r qingxia_bwa.final.scaffolds.fasta -hco 5.0 -c 1.5 -l 20000 -ml 20000

**Comment by wenjiexiaomeng** [comment]
Hi,

I finished it by your suggestions, and I will try with different parameters.
Thanks a lot!
(I confounded the two parameters -d and -q...)

Best,
Wenjie

**Comment by mahulchak** [comment]
Cool
