### ISSUE TITLE
Add --version or -V flag

### ISSUE THREAD

**Issue by tseemann** [mahulchak/quickmerge#29]
```
% quickmerge -V
quickmerge 0.2

% echo $?
0
```
(to stdout. and clean exit code)

**Comment by tseemann** [comment]
🎈 1 year anniversary 😃 

I upgraded the `brew` package to 0.3

**Comment by mahulchak** [comment]
thanks for the reminder. it's on my radar now :)

**Comment by mahulchak** [comment]
quickmerge -h or quickmerge --help will now print the version. thanks for your feedback.
