### ISSUE TITLE
terminate called after throwing an instance of 'std::out_of_range'

### ISSUE THREAD

**Issue by MichelMoser** [mahulchak/quickmerge#3]
Hi, 
When running quickmerge for a large genome i get following error: 

```
...
ctg7180000048769        ctg7180000048768        1        Backbone_3247  -1      ctg7180000048769        1
ctg7180000049599         Backbone_10703 1       ctg7180000049599        -1
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551359) > this->size() (which is 118601)
Aborted
```
The number of sequences which get outputted from the quickmerge run is less than the number of lines in the anchor_summary.txt file, so the error must be while merging. Also no fasta file gets created.

When i cut down the .rq.delta file to half of the size, the error disappears and i get normal output (of course missing some valuable merged contigs).

I am using commit 3f950d89f1ae9f69c2278a0302f34609f2cc56f6.

Shall i send you my files?

Thank you, 
michel

**Comment by mahulchak** [comment]
Hi Michel,

This error typically means that either white space in fasta names or line
breaks in the fasta sequences have not been removed (or that the order of
two fasta files following -r and -q options in quickmerge command line has
been switched). If none of those happened in your case, I will be happy to
take a look at your inputs. Also, I am about to commit a fix to the source
code. May be you can give the new source code a shot before I take a look
at your inputs?

Cheers,
Mahul

On Sat, Jan 9, 2016 at 3:13 AM, MichelMoser <notifications@github.com>
wrote:

> Hi,
> When running quickmerge for a large genome i get following error:
>
>
> ctg7180000048769        ctg7180000048768        1        Backbone_3247  -1      ctg7180000048769        1
> ctg7180000049599         Backbone_10703 1       ctg7180000049599        -1
> terminate called after throwing an instance of 'std::out_of_range'
>   what():  basic_string::substr: __pos (which is 18446744073709551359) > this->size() (which is 118601)
> Aborted
>
> The number of sequences which get outputted from the quickmerge run is
> less than the number of lines in the anchor_summarytxt file, so the error
> must be while merging Also no fasta file gets created
>
> When i cut down the rqdelta file to half of the size, the error disappears
> and i get normal output (of course missing some valuable merged contigs)
>
> I am using commit 3f950d8
> <https://github.com/mahulchak/quickmerge/commit/3f950d89f1ae9f69c2278a0302f34609f2cc56f6>
>
> Shall i send you my files?
>
> Thank you,
> michel
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mahulchak/quickmerge/issues/3>.
>



-- 
Mahul Chakraborty
Emerson lab <http://emersonlab.org/>
Department of Ecology and Evolutionary Biology
University of California-Irvine
Phone: 949 824 9559
Fax:
Github: https://github.com/mahulchak

**Comment by MichelMoser** [comment]
Hi Mahul, 
i doublechecked spaces in headers and line-breaks and order of genomes. Seems to be all fine. 
I will try your new commit as soon as i get it.

**Comment by mahulchak** [comment]
Hi Michel,
please check the current version to see if it fixes the issue. If not, I will be happy to check the issue using your input files.

**Comment by shameem356** [comment]
Hello ,

I am also facing the same problem.When I ran quickmerge  first time it worked fine with the following command1.But when I change the reference and query( Command 2 : swapped query & reference ) it showing the  error std::out_of_range error.I am using latest build.Please let me know how can I solve the issue.

**command 1**
nucmer -l 100 -prefix out New_CspixV2gen.fa 0x_spix.fa
delta-filter -i 95 -r -q out.delta > out.rq.delta
quickmerge -d out.rq.delta  -r New_CspixV2gen.fa -q 10x_spix.fa -hco 5.0 -c 1.5 -l 1000000 -ml 6000 


**command 2**
nucmer -l 100 -prefix out 10x_spix.faNew_CspixV2gen.fa
delta-filter -i 95 -r -q out.delta > out.rq.delta
quickmerge -d out.rq.delta -r 10x_spix.fa -q New_CspixV2gen.fa -hco 5.0 -c 1.5 -l 1000000 -ml 6000

**Comment by KZhangCN** [comment]
Hello,
I got the same error. However, unlike the problem reported by shameem365, it showed the error in both commands (assemble1 as the ref and assemble2 as the query, and vice visa). I used the similar commands as presented by shameem356. Could you help me solve this problem?

**Comment by mahulchak** [comment]
could you please post your nucmer and quickmerge commands?

**Comment by KZhangCN** [comment]
Hi, mahulchak, I saw your reply in another issue: "Quickmerge currently accepts only fasta files in which sequences are present in single line". 
Sorry, I missed it! I will try to reformat the fasta and run the workflow again. If any error occurs, I would let you know. Thanks.

**Comment by mahulchak** [comment]
the current version doesn't require that. How are your sequence names?
Could you give an example from each of your fasta files (reference and
query)?

**Comment by KZhangCN** [comment]
Sorry, I checked the title lines of the fasta file, and found that serveral lines contain the white spaces. (I forgot that I merged the contigs from different files, some of them contains unnecessary white spaces.)
I have removed them and found that Quickmerge works fine!
Thank you for your kindly help! So long I haven't met such a responsible and warmhearted author like you...
