### ISSUE TITLE
better naming of output (intermediate) files

### ISSUE THREAD

**Issue by lsterck** [mahulchak/quickmerge#31]
Hi,

you have a great software here. I just wanted to bring something up to perhaps make it even better. 
I think it might be useful to name the files the program creates more uniform. I mean: name them all using the prefix that is given on the cmdline. I notice that some files have a general name (eg. self_oneline.fa or the merged.fasta outputfile) which causes them to be overwritten when I run several jobs at once (where each uses a different prefix though).

thx and keep up the good work.

**Comment by mahulchak** [comment]
Thanks for your feedback @lsterck . Quickmerge now has a prefix option :)
