### ISSUE TITLE
Segmentation fault with larger heterozygous input

### ISSUE THREAD

**Issue by ViriatoII** [mahulchak/quickmerge#42]
Hi,

I'm having segmentation fault at the quickmerger stage after using the merge_wrapper. Nucmer and everything before worked fine and created normal outputs, including oneline.fa files.

```-rw-r--r-- 1 guerrer QGGP    5474315 Jul 22 13:23 aln_summary_out.tsv
-rw-r--r-- 1 guerrer QGGP    2456765 Jul 22 13:23 anchor_summary_out.txt
-rw-r--r-- 1 guerrer QGGP 1049205219 Jul 22 13:22 hybrid_oneline.fa
-rw-r--r-- 1 guerrer QGGP          0 Jul 22 13:23 merged_out.fasta
-rw-r--r-- 1 guerrer QGGP   91857760 Jul 22 13:22 out.delta
-rw-r--r-- 1 guerrer QGGP    9563554 Jul 22 13:22 out.rq.delta
-rw-r--r-- 1 guerrer QGGP    3982704 Jul 22 13:23 param_summary_out.txt
-rw-r--r-- 1 guerrer QGGP 1343593069 Jul 22 13:22 self_oneline.fa
```

The quickmerge error must have to do with my input self_oneline.fa, it's the only new thing.

Now, instead of rerrunning the whole wrapper, I'm just running this command: 

> quickmerge -d out.rq.delta -q hybrid_oneline.fa -r self_oneline.fa -hco 5.0 -c 1.5 -l 0 -ml 5000 -p out

Results:    

       File                   size        First line(fasta header)
    hybrid_oneline.fa      1049205219        >1
    self_oneline.fa        845417800         >tig00035160                Success!

    hybrid_oneline.fa      1049205219        >1
    self_oneline.fa        1343593069        >tig00000003_pilon     Segmentation fault (core dumped)

The only difference is the size and origin of the self file. The successful one is a canu assembly after using purge haplotigs to eliminate haplotigs (alternative diploid contigs ). The unsuccessful one is a canu assembly but without using purge haplotigs (thus it is heterozygous/diploid).

Is my problem derived from the input sizes? Or maybe from heterozygosity?

**Comment by mahulchak** [comment]
You can check if it is due to file size by running the command with

/usr/bin/time -v

It'll show you the memory usage for the two different assembly sizes.

Generally I don't recommend use of heterozygous assemblies for assembly
merging. Better to use the assembly without haplotigs.
