### ISSUE TITLE
bad ELF interpreter

### ISSUE THREAD

**Issue by albodrug** [mahulchak/quickmerge#5]
Hello, 

I have an error when using quickmerge. The compilation looks like it worked.

```
~/progs/quickmerge/merger 
(master)>make 
make: `quickmerge' is up to date.
```

Upon trying to launch it:

```
~/progs/quickmerge/merger 
(master)>./quickmerge
-bash: ./quickmerge: /software/lib64/ld-linux-x86-64.so.2: bad ELF interpreter: No such file or directory
```

Is quickmerge a 32 bit application? Is there a way to force the compilation with the interpreter that is available to me? (It's a cluster I can't install libraries on it easily myself).
Thanks!

**Comment by mahulchak** [comment]
Hi ,
Could you try adding "-m64" to the Makefile and then run make again ?
E.g. the modified Makefile line should look like this

g++ -m64 -O3 -Wall -o quickmerge quickmerge.cpp qmergelib.cpp -I.

see if this solves the issue.
Mahul

**Comment by albodrug** [comment]
I actually can't compile at all. 

```
~/progs/quickmerge-master/merger 
>make
g++ -m64 -O3 -Wall -o quickmerge quickmerge.cpp qmergelib.cpp -I.
qmergelib.cpp: In function 'void ctgJoiner(asmMerge&, asmMerge&, fastaSeq&, fastaSeq&, fastaSeq&)':
qmergelib.cpp:996: error: 'tempRef_st' was not declared in this scope
make: *** [quickmerge] Error 1
```

But if I ` touch quickmerge` then run `make`, I have the 'up to date' message while the quickmerge file is actually an empty file. 

```
~/progs/quickmerge-master/merger 
>touch quickmerge
~/progs/quickmerge-master/merger 
>make
make: `quickmerge' is up to date.
~/progs/quickmerge-master/merger 
>ls -lh
total 60K
-rw-r--r-- 1 abodrug p70694  118 May 12 09:57 Makefile
-rw-r--r-- 1 abodrug p70694 3.1K May  6 07:40 qmerge.h
-rw-r--r-- 1 abodrug p70694  46K May  6 07:40 qmergelib.cpp
-rw-r--r-- 1 abodrug p70694    0 May 12 10:02 quickmerge
-rw-r--r-- 1 abodrug p70694 3.4K May  6 07:40 quickmerge.cpp
```

I tried with gcc compiler 4.4.7 and 4.9.3
Should I try using another version?

**Comment by mahulchak** [comment]
Ok. Remove the -O3 flag and try it again.
 g++ -m64 -Wall -o quickmerge quickmerge.cpp qmergelib.cpp -I.
It should compile under all gcc because it does not use any special
library. I just compiled it using gcc 4.8.2 and it worked fine.

**Comment by mahulchak** [comment]
I just noticed that some of the variable declarations went missing during a
fork merging. I have fixed it. Could you please re-download it? (git pull
should work)

**Comment by albodrug** [comment]
Hey Mahul, 
Getting the last the git repo version today and setting -m64 solved the compiling and the bad ELF interpreter problem respectively. 
Thanks a lot for your help
