### ISSUE TITLE
running quickmerge using multiple threads

### ISSUE THREAD

**Issue by tangerzhang** [mahulchak/quickmerge#6]
Is there any parameter to speed up quickmerge progress, for example multiple threads?
Thanks

**Comment by jgbaldwinbrown** [comment]
Hi,

Actually, true to its name, quickmerge itself runs in just a few seconds -- the slow part of the code is MUMmer, which must run before quickmerge can finish.  Unfortunately, MUMmer is designed to be single-threaded, but there is at least one way to speed it up: installing e-mem (http://bioinformatics.oxfordjournals.org/content/early/2014/10/16/bioinformatics.btu687.full.pdf) is known to improve MUMmer's speed.  A distribution of e-mem is available in the Quast 4 distribution (http://quast.bioinf.spbau.ru/).  It is not out of the question that we may try to integrate e-mem into a later version of the quickmerge pipeline, though for now, you will have to compile your own version of e-mem and insert it into your MUMmer /bin/ (follow e-mem's installation instructions).  Another alternative might be to split your reference genome into multiple files, then run MUMmer separately on each file in parallel, then merge the resulting .delta files (not sure how hard that is), then continue the pipeline by running the delta-filter -r -q step and quickmerge.  Again, Quast 4 comes with a version of MUMmer that has a similar parallelization option added, though I have not tested its use with quickmerge.

Hope that helps.  Good luck, and feel free to tell us how it's going or ask for more help.

**Comment by ViriatoII** [comment]
Hey,

Are you going to update quickmerge with the new MUMmer4, which finally has paralization?
