### ISSUE TITLE
An error when running quickmerge

### ISSUE THREAD

**Issue by tangerzhang** [mahulchak/quickmerge#7]
Hello,
I had a problem when running quickmerge. The error message like below:
"
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 3152) > this->size() (which is 0)
run.sh: line 5: 26095 Aborted                 quickmerge -d out.rq.delta -q secondary_contigs.fasta -r pb.only.fasta -hco 5.0 -c 1.5 -l n
"
I know that you already have an explanation for this issue: probably because of the mis-formated fasta header line with white space.
However, I checked my two fasta files and there are no white space in the header line. Thus I guess the mis-formated fasta file is not my case.
I attached what my files looks like:

less pb.only.fasta
\>000000F
CACCTCGTCGGGGAAGGAGATAGCTTCCTCACGCCAT
less hy.asm.fasta
\>scf7180000332062
GAGGAGACACCGTGCTACTAGGTGGTTGTGCCACCGGAGCAGCCACACCCTTTAACAGGT

Looking forward to your suggestion!
Thanks a lot!

**Comment by mahulchak** [comment]
Hi,
did you change 'n' to a number (i.e. what is the value of l)? Another thing
which we mention and would like to rule out here is that your fasta files
do not have line breaks in them. Could you check that? PBcR assemblies
typically have line breaks in them.

**Comment by tangerzhang** [comment]
OK, I see.
I have one fasta file which has break lines; while another does not have
break lines.
Thanks for your clarification!


2016-05-24 17:01 GMT+08:00 Mahul Chakraborty <notifications@github.com>:

**Comment by jgbaldwinbrown** [comment]
Hi,
Glad to hear that it's working for you.  In the future, you can pretty easily avoid these problems by never calling the quickmerge executable, and instead using the "merge_wrapper.py" wrapper for the program.  This runs MUMmer and delta-filter for you (you can turn this part off if those steps are complete), and it will auto-generate correctly formatted fasta files if it detects problems with your input fasta files, i.e. line breaks.
