### ISSUE TITLE
fasta parsing problems

### ISSUE THREAD

**Issue by albodrug** [mahulchak/quickmerge#8]
Hello!
On some of my genome fastas I get this error
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 764951) > this->size() (which is 755524)
-bash: line 166: 10789 Aborted                 (core dumped)
```

My sequences are renamed with numbers like >1, >2 ... >n in both genome fastas.  I checked for special characters in sequences by grepping:
' ' - space: none in the file
'\t' - tabs: non in the file
'[^ACTGN]' - anything non nucleotide: i only get the headers.
So my fastas contain '>', ints, A, C, T, N and $. 
Considering quickmerge works perfectly with my other datasets, I am pretty sure the issue is my fasta files. I am also careful to use the same genome as query in both nucmer and quickmerge. 

Would you have any suggestion for other possible errors in my fasta files or other reasons why this error would appear?

Thanks, 
Alex

edit: I am trying with the wrapper. Saw similar issue below.

**Comment by mahulchak** [comment]
Hi Alex,
Does this error persist if you use a more restrictive value of the l
parameter? E.g. if you were using 1Mb as the value of l, does the issue
persist if you use a longer cutoff (e.g. 5Mb)?
Mahul

**Comment by albodrug** [comment]
Hi Mahul, 
My setting for l cutoff size is only 480kbp. I tried running the wrapper, It did not generate formatted versions of the original fastas yet failed once again. My other dataset has l=1.8Mbp and works perfectly. 
Does having identical names in query and reference affect quickmerge? 

-Alex

**Comment by jgbaldwinbrown** [comment]
Hi Alex,

Sorry for the delay.  Yes, due to the way that the maps are accessed during merging, it is important that every sequence in the assemblies have a unique name.  We may patch the wrapping program to fix duplicate names in the future, but for now, you will have to fix that yourself.
