### ISSUE TITLE
#!/usr/bin/env python

### ISSUE THREAD

**Issue by JohnUrban** [mahulchak/quickmerge#9]
Hi Mahul,

Just a note -- I had to change this in merge_wrapper.py:
#!/usr/bin/python
to
#!/usr/bin/env python

for it to work.

It might be good to change this in your code as the latter will figure out the correct location of python on anyone's system.

best,

John

**Comment by mahulchak** [comment]
Hi John,
That's a good suggestion. Will do.
Mahul
